"""
Django settings for turf_backend project.
Generated by 'django-admin startproject' using Django 4.2.10
"""

from pathlib import Path
from datetime import timedelta
from decouple import config

# --------------------------------------------------
# BASE DIR
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# --------------------------------------------------
# GOOGLE CLOUD STORAGE (Media files in production)
# Cloud Run filesystem is ephemeral — use GCS for images
# --------------------------------------------------
import os
GCS_BUCKET = os.environ.get("GCS_BUCKET_NAME", "")

if GCS_BUCKET:
    # Django 4.2+ / 5.x format
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": GCS_BUCKET,
                "querystring_auth": False,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    GS_BUCKET_NAME = GCS_BUCKET
    MEDIA_URL = f"https://storage.googleapis.com/{GCS_BUCKET}/"



# --------------------------------------------------
# SECURITY
# --------------------------------------------------
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-change-this-in-production"
)

DEBUG = config("DEBUG", default=False, cast=bool)

APPEND_SLASH = False

ALLOWED_HOSTS = [
    "localhost",
    # "127.0.0.1",
    "*"
]


# --------------------------------------------------
# APPLICATIONS
# --------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'corsheaders',


    # Local apps
    'core',
]


# --------------------------------------------------
# MIDDLEWARE (⚠️ ORDER IMPORTANT)
# --------------------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',   # ✅ MUST be first (top)
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# --------------------------------------------------
# CORS CONFIG (Frontend ↔ Backend)
# --------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = True
# OR (recommended later)
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
# ]


# --------------------------------------------------
# URLS / WSGI
# --------------------------------------------------
ROOT_URLCONF = 'turf_backend.urls'

WSGI_APPLICATION = 'turf_backend.wsgi.application'


# --------------------------------------------------
# TEMPLATES
# --------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# --------------------------------------------------
# DATABASE (Supabase PostgreSQL)
# --------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME", default="postgres"),
        "USER": config("DB_USER", default="postgres"),
        "PASSWORD": config("DB_PASSWORD", default=""),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}


# --------------------------------------------------
# PASSWORD VALIDATION
# --------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

AUTH_USER_MODEL = 'core.AppUser'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# --------------------------------------------------
# INTERNATIONALIZATION
# --------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --------------------------------------------------
# STATIC FILES
# --------------------------------------------------
STATIC_URL = 'static/'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = BASE_DIR / 'staticfiles'


# --------------------------------------------------
# DRF + JWT CONFIG
# --------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
# }

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),    # 1 day access token
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),   # 7 days refresh token
    "ROTATE_REFRESH_TOKENS": True,                 # new refresh token on every refresh
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),             
}

import os
from dotenv import load_dotenv

load_dotenv()

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST      = config("SMTP_HOST", default="smtp.gmail.com")
EMAIL_PORT      = config("SMTP_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("SMTP_USER", default="")
EMAIL_HOST_PASSWORD = config("SMTP_PASS", default="")

EMAIL_USE_TLS = config("SMTP_TLS", default=True, cast=bool)
EMAIL_USE_SSL = False

DEFAULT_FROM_EMAIL = f"TurfApp <{EMAIL_HOST_USER}>"


# --------------------------------------------------
# RAZORPAY CONFIG

RAZORPAY_KEY_ID = config("RAZORPAY_KEY_ID", default="")
RAZORPAY_KEY_SECRET = config("RAZORPAY_KEY_SECRET", default="")


# --------------------------------------------------
# WHATSAPP CONFIG

WHATSAPP_API_URL = config("WHATSAPP_API_URL", default="https://103.229.250.150/unified/v2/send")
WHATSAPP_CLIENT_ID = config("WHATSAPP_CLIENT_ID", default="")
WHATSAPP_CLIENT_PASSWORD = config("WHATSAPP_CLIENT_PASSWORD", default="")
WHATSAPP_FROM_NUMBER = config("WHATSAPP_FROM_NUMBER", default="")
WHATSAPP_USER_ID = config("WHATSAPP_USER_ID", default=3, cast=int)