# Generated by Django 6.0.3 on 2026-03-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='is_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
