# Generated by Django 5.2.10 on 2026-03-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_turf_is_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='retire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='retire_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='retire_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
