# Generated by Django 6.0.3 on 2026-03-31 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appuser_retire_appuser_retire_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTurf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.turf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_turfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'turf')},
            },
        ),
    ]
