# Generated by Django 6.0.3 on 2026-04-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_favoriteturf'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
