# Generated by Django 6.0.3 on 2026-04-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_user_email_booking_user_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='retire',
            field=models.IntegerField(default=0),
        ),
    ]
