# Generated by Django 5.2.10 on 2026-05-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_turf_retire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
