# Generated by Django 5.2.10 on 2026-06-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_appuser_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Festival', 'Festival'), ('Sports', 'Sports'), ('Other', 'Other')], default='Sports', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('organized_by', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('agenda', models.TextField(blank=True)),
                ('vips', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('featured', 'Featured'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('bg_color', models.CharField(blank=True, default='#a5b4fc', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date', '-created_at'],
            },
        ),
    ]
