# Generated by Django 5.2.10 on 2026-06-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_eventreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
    ]
